---
- name: Start VOLTTRON as Service
  ansible.builtin.systemd:
    name: volttron
    daemon_reload: yes
    enabled: yes
    state: started
  when: (volttron_was_running | default(false)) and make_volttron_service is defined and make_volttron_service | bool
  become: yes

- name: Start VOLTTRON Not as Service
  volttron.deployment.volttron_platform:
    volttron_root: "{{volttron_root}}"
    volttron_home: "{{volttron_home}}"
    state: running
  when: (volttron_was_running | default(false)) and make_volttron_service is not defined or not make_volttron_service | bool

- name: Wait for VOLTTRON to start
  ansible.builtin.shell:
    cmd: "{{ volttron_venv }}/bin/vctl status"
  register: volttron_status_result
  when: volttron_was_running | default(false)
  until: volttron_status_result.rc == 0
  retries: 10
  delay: 3

- name: Shutdown VOLTTRON as Service
  ansible.builtin.systemd:
    name: volttron
    enabled: yes
    state: stopped
  when: not (volttron_was_running | default('false')) and make_volttron_service is defined and make_volttron_service | bool
  become: yes

- name: Shutdown VOLTTRON Not as Service
  volttron.deployment.volttron_platform:
    volttron_root: "{{volttron_root}}"
    volttron_home: "{{volttron_home}}"
    state: stopped
  when: not (volttron_was_running | default('false')) and make_volttron_service is not defined or not make_volttron_service | bool