---
- name: Install Economizer RCx Config
  ansible.builtin.shell:
    cmd: >
      echo "{{ value | to_json }}" |
      {{ volttron_venv }}/bin/vctl config store rcx.{{ key }} config /dev/stdin
  vars:
    key: "{{ item.device.unit | dict2items | map(attribute='key') | first }}"
    value: "{{ item | to_json }}"

- name: Install Economizer RCx Agent
  volttron.deployment.volttron_agent:
    volttron_root: "{{ volttron_root }}"
    volttron_home: "{{ volttron_home }}"
    volttron_venv: "{{ volttron_venv }}"
    agent_vip_id: "rcx.{{ key }}"
    agent_spec: "{{ this_spec }}"
  vars:
    - key: "{{ item.device.unit | dict2items | map(attribute='key') | first }}"
    - this_spec: {
                   agent_source: "{{ ansible_env.HOME }}/volttron-pnnl-applications/EnergyEfficiency/EconomizerRCxAgent/",
                   agent_state: 'present',
                   agent_enabled: True,
                   agent_priority: 50,
                   agent_running: true,
                   agent_tag: 'rcx',
                   skip_requirements: False,
                   force_install: False
                 }
